### ISSUE TITLE
Can't install on Sierra 10.12.1

### ISSUE THREAD

**Issue by gperdomor** [vapor/homebrew-tap#2]
brew install vapor/tap/toolbox
==> Installing toolbox from vapor/tap
==> Downloading https://github.com/vapor/toolbox/archive/1.0.3.tar.gz
Already downloaded: /Users/myuser/Library/Caches/Homebrew/toolbox-1.0.3.tar.gz
==> swift build -c release
Last 15 lines from /Users/myuser/Library/Logs/Homebrew/toolbox/01.swift:
2016-10-30 13:21:31 -0300

swift build -c release

swift-build: error: invalid inferred toolchain: could not find `clang` at expected path /private/tmp/toolbox-20161030-2619-1q97v1g/toolbox-1.0.3/clang

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/vapor/homebrew-tap/issues

**Comment by taglia3** [comment]
Hi,

Same error here

**Comment by tanner0101** [comment]
I'm also seeing this error. Use the toolbox script for now:

``` sh
curl -sL toolbox.vapor.sh | bash
```

**Comment by tiagodocouto** [comment]
same problem!
`curl -sL toolbox.vapor.sh | bash` worked here!

**Comment by tanner0101** [comment]
Just pushed a fix for this. It was an issue with `$CC` inside of home-brew.

A Swift bug has been opened: https://bugs.swift.org/browse/SR-3151
