### ISSUE TITLE
getting around corporate policy

### ISSUE THREAD

**Issue by madsteer** [vapor/homebrew-tap#20]
Hi. I have a Mac at work with Xcode installed, but we don't allow homebrew to work.  I can get permission to clone this repo.  Would cloning this repo somehow allow me to install the vapor toolbox on my Mac (via brew command or otherwise)?

Thanks,

**Comment by tanner0101** [comment]
Hi @madsteer. Homebrew is not required to use Vapor Toolbox. You can download a pre-compiled Vapor Toolbox executable from [vapor/toolbox/releases](https://github.com/vapor/toolbox/releases). The latest non-beta release as of now is [Toolbox `3.1.10`](https://github.com/vapor/toolbox/releases/tag/3.1.10). The download comes with install instructions.

You can also clone https://github.com/vapor/toolbox and build the toolbox from scratch using `swift build -c release`.

**Comment by vzsg** [comment]
But how can one install libressl, which will be a required dependency of the Vapor projects anyway, without Homebrew? I think that would be an interesting question to cover.
