### ISSUE TITLE
Support Linux platform

### ISSUE THREAD

**Issue by segabor** [vapor/homebrew-tap#25]
Add Linux support for the toolbox binaries on Linux too. Currently Homebrew installs macOS binary.

**Comment by tanner0101** [comment]
I think once we are merged into homebrew-core this will happen automatically: https://github.com/Homebrew/homebrew-core/pull/42436/files

Currently the way we distribute binaries is very manual

**Comment by 0xTim** [comment]
The toolbox is now merged into homebrew core so this should work
