### ISSUE TITLE
error: cannot convert value of type 'Option<_>' to specified type 'String'

### ISSUE THREAD

**Issue by niklassaers** [vapor/homebrew-tap#26]
Homebrew is up-to-date as of today (2019-12-12), running on Catalina with Xcode 11.3 installed and Swift 5.1.3

Getting five of these during ```brew install vapor/tap/vapor-beta```:

```
toolbox-18.0.0-beta.19/Sources/CloudCommands/Deploy.swift:9:10: error: cannot convert value of type 'Option<_>' to specified type 'String'
        @Option(name: "env", short: "e")
```

01.swift attached

[01.swift.zip](https://github.com/vapor/homebrew-tap/files/3957060/01.swift.zip)

**Comment by stuartbreckenridge** [comment]
Also having the same issue.

**Comment by rpstro02** [comment]
Same issue.  Running brew install vapor/tap/vapor-beta on Mojave 10.14.5, Swift 5.1.3.

**Comment by bynelus** [comment]
Same here.

**Comment by bblacey** [comment]
ditto

**Comment by NickSet** [comment]
Having the same issue with Xcode 11.3, Swift 5.1.3, and Catalina 10.15.2.

**Comment by bblacey** [comment]
@NickSet, FYI, there are instructions in the pull request above that will enable you to work around the problem until such time the team integrates the pull request.

**Comment by vzsg** [comment]
Which should be now, I mean 24 minutes ago.

**Comment by 0xTim** [comment]
Pretty sure this was fixed
