### ISSUE TITLE
swift version problem of installing vapor-beta

### ISSUE THREAD

**Issue by GuangyuLeo** [vapor/homebrew-tap#28]
==> Installing vapor-beta from vapor/tap
==> Downloading https://github.com/vapor/toolbox/archive/18.0.0-beta.27.tar.gz
Already downloaded: /Users/liaoyanxi/Library/Caches/Homebrew/downloads/a17328593022736d0658058db21d6d516deb7c561c088ed71d02f0949e905954--toolbox-18.0.0-beta.27.tar.gz
==> swift build --disable-sandbox
Last 15 lines from /Users/liaoyanxi/Library/Logs/Homebrew/vapor-beta/01.swift:
2020-03-05 12:56:21 +0800

swift
build
--disable-sandbox

Fetching https://github.com/apple/swift-log.git
Fetching https://github.com/apple/swift-nio.git
Fetching https://github.com/jpsim/Yams.git
Fetching https://github.com/vapor/console-kit.git
Fetching https://github.com/tanner0101/mustache.git
https://github.com/vapor/console-kit.git @ master: error: package at 'https://github.com/vapor/console-kit.git' @ de99d83c9f3c298371002729cc0601e4b5d9e0c9 is using Swift tools version 5.2.0 but the installed version is 5.1.0

=======================================================================
My Xcode version is 11.3.1 but I downloaded swift 5.2 toolchain and used swiftenv to change my global and local swift version to 5.2.

**Comment by 0xTim** [comment]
Just to confirm - `swift --version` shows 5.2? If so I suspect Swiftenv doesn't work with Homebrew

**Comment by GuangyuLeo** [comment]
> Just to confirm - `swift --version` shows 5.2? If so I suspect Swiftenv doesn't work with Homebrew

I could build the beta toolbox manually by `swift build --disable-sandbox`.
The auto build thread was created by Ruby `system "swift", "build", "--disable-sandbox"`when I used Hombrew to install it. 
Maybe the `system` function of ruby will not load current env or PATH. I'm not sure if this is the problem reason of this issue.

**Comment by tanner0101** [comment]
Yeah I think this requires Swift 5.2 to be installed via Xcode beta and selected as the current command line tools. If we can figure out a way around that I'd be happy to add. But Xcode beta seems to be required for SPM to work correctly in general, so that seems like the best solution.

**Comment by 0xTim** [comment]
@tanner0101 why don't we distribute the binary?

**Comment by tanner0101** [comment]
@0xTim afaik homebrew handles that for us once we become an official tool.

**Comment by 0xTim** [comment]
Ah ok, that should help then
