### ISSUE TITLE
Beta installation on Mac Fails

### ISSUE THREAD

**Issue by fahied** [vapor/homebrew-tap#29]
While installing the beta version using command below

brew install vapor-beta

I get the following error
`
https://github.com/vapor/console-kit.git @ master: error: package at 'https://github.com/vapor/console-kit.git' @ de99d83c9f3c298371002729cc0601e4b5d9e0c9 is using Swift tools version 5.2.0 but the installed version is 5.1.0
`
Even though I have latest swift-tool chain installed 
Apple Swift version 5.2 (swift-5.2-RELEASE)
Target: x86_64-apple-darwin19.3.0

and had followed apple instruction to export the path
`export PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:"${PATH}"`

**Comment by 0xTim** [comment]
@fahied unfortunately Homebrew doesn't respect other toolchains from Xcode or setting the path like that. If you install Xcode 11.4 it should work
