### ISSUE TITLE
Install vapor-beta fails

### ISSUE THREAD

**Issue by m-y-n-o-n-a** [vapor/homebrew-tap#31]
brew install vapor/tap/vapor-beta
==> Installing vapor-beta from vapor/tap
==> Downloading https://github.com/vapor/toolbox/archive/18.0.0-beta.27.tar.gz
Already downloaded: /Users/kaeru/Library/Caches/Homebrew/downloads/a17328593022736d0658058db21d6d516deb7c561c088ed71d02f0949e905954--toolbox-18.0.0-beta.27.tar.gz
==> swift build --disable-sandbox
Last 15 lines from /Users/kaeru/Library/Logs/Homebrew/vapor-beta/01.swift:
2020-04-18 12:19:01 +0200

swift
build
--disable-sandbox

error: terminated(72): TERM=xterm-256color USER=kaeru HOMEBREW_CORE_DEFAULT_GIT_REMOTE=https://github.com/Homebrew/homebrew-core CMAKE_INCLUDE_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers HOMEBREW_AUTO_UPDATE_CHECKED=1 CARGO_HOME=/Users/kaeru/Library/Caches/Homebrew/cargo_cache TMP=/private/tmp HOMEBREW_LOGS=/Users/kaeru/Library/Logs/Homebrew HOMEBREW_LIBRARY=/usr/local/Homebrew/Library CMAKE_PREFIX_PATH=/usr/local HOMEBREW_ANALYTICS_USER_UUID=5BCA10C2-6DFC-4ACE-AEBF-4191D3027679 HOMEBREW_RUBY_PATH=/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby CMAKE_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries HOMEBREW_SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk CXX=clang++ MAKEFLAGS=-j12 HOMEBREW_ERROR_PIPE=/private/tmp/homebrew20200418-10412-1cff5zj/socket HOMEBREW_OS_VERSION=macOS 10.15.4 HOMEBREW_DEFAULT_TEMP=/private/tmp HOMEBREW_BREW_FILE=/usr/local/bin/brew HOMEBREW_MACOS_VERSION=10.15.4 LIBRARY_PATH=/usr/local/lib OBJCXX=clang++ OBJC=clang TEMP=/private/tmp GOCACHE=/Users/kaeru/Library/Caches/Homebrew/go_cache HOMEBREW_CXX=clang++ SHLVL=0 SHELL=/bin/bash SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk HOMEBREW_CELLAR=/usr/local/Cellar HOMEBREW_ISYSTEM_PATHS=/usr/local/include:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers HOMEBREW_USER_AGENT_CURL=Homebrew/2.2.13 (Macintosh; Intel Mac OS X 10.15.4) curl/7.64.1 LOGNAME=kaeru HOMEBREW_USER_AGENT=Homebrew/2.2.13 (Macintosh; Intel Mac OS X 10.15.4) TMPDIR=/private/tmp HOMEBREW_COMMAND_DEPTH=2 HOMEBREW_ARCHFLAGS= HOMEBREW_PRODUCT=Homebrew HOMEBREW_BREW_GIT_REMOTE=https://github.com/Homebrew/brew CURL_HOME=/Users/kaeru HOMEBREW_ENV=super HOMEBREW_SYSTEM=Macintosh HOMEBREW_MINIMUM_GIT_VERSION=2.14.3 HOMEBREW_ANALYTICS_ID=UA-76679469-1 HOMEBREW_CACHE=/Users/kaeru/Library/Caches/Homebrew HOMEBREW_VERSION=2.2.13 HOMEBREW_CC=clang HOMEBREW_DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer CC=clang HOMEBREW_RUBY_WARNINGS=-W0 SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.BqFVG1xsWI/Listeners HOMEBREW_DEFAULT_CACHE=/Users/kaeru/Library/Caches/Homebrew HOMEBREW_FORMULA_PREFIX=/usr/local/Cellar/vapor-beta/18.0.0-beta.27 _JAVA_OPTIONS=-Duser.home=/Users/kaeru/Library/Caches/Homebrew/java_cache LC_ALL=en_US.UTF-8 HOMEBREW_CORE_GIT_REMOTE=https://github.com/Homebrew/homebrew-core HOMEBREW_GIT_CONFIG_FILE=/usr/local/Homebrew/.git/config HOMEBREW_DEPENDENCIES= CPATH=/usr/local/include HOMEBREW_PREFIX=/usr/local ACLOCAL_PATH=/usr/local/share/aclocal HOMEBREW_OPT=/usr/local/opt HOMEBREW_TEMP=/private/tmp HOMEBREW_BOTTLE_DEFAULT_DOMAIN=https://homebrew.bintray.com PWD=/Users/kaeru HOMEBREW_DEFAULT_LOGS=/Users/kaeru/Library/Logs/Homebrew HOMEBREW_CURL=curl PATH=/usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/bin:/bin:/usr/sbin:/sbin HOMEBREW_BOTTLE_DOMAIN=https://homebrew.bintray.com HOMEBREW_CC_LOG_PATH=/Users/kaeru/Library/Logs/Homebrew/vapor-beta/01.swift HOMEBREW_GIT=git HOMEBREW_PROCESSOR=Intel __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x5C HOMEBREW_LIBRARY_PATHS=/usr/local/lib:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries HOME=/private/tmp/vapor-beta-20200418-11078-1vyk9ee/toolbox-18.0.0-beta.27/.brew_home HOMEBREW_CCCFG=sa HOMEBREW_OPTIMIZATION_LEVEL=Os HOMEBREW_PREFER_CLT_PROXIES=1 PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15 HOMEBREW_OPTFLAGS=-march=nehalem HOMEBREW_REPOSITORY=/usr/local/Homebrew HOMEBREW_MACOS_VERSION_NUMERIC=101504 HOMEBREW_BREW_DEFAULT_GIT_REMOTE=https://github.com/Homebrew/brew xcrun --sdk macosx --find xctest output:
    xcrun: error: unable to find utility "xctest", not a developer tool or in PATH
    

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/vapor/homebrew-tap/issues

These open issues may also help:
Update vapor-beta.rb to include latest toolbox release https://github.com/vapor/homebrew-tap/pull/30

**Comment by 0xTim** [comment]
Can you try running `sudo xcode-select -s /Applications/Xcode.app` and then trying again?

**Comment by shindakioku** [comment]
@0xTim It works! thank you!
